server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # VideoSearch
        - id: video-search
          uri: ${services.videosearch.url}    # http://localhost:8081
          predicates:
            - Path=/video-service/**          # /video-service/** 로 시작하는 요청 전부
          filters:
            - RemoveRequestHeader=Cookie      # Cookie 헤더만 삭제

        # Encyclopedia
        - id: encyclopedia
          uri: ${services.encyclopedia.url}  # http://localhost:8082
          predicates:
            - Path=/encyclopedia-service/**
          filters:
            - RemoveRequestHeader=Cookie

        # News
        - id: news
          uri: ${services.news.url}          # http://localhost:8083
          predicates:
            - Path=/news-service/**
          filters:
            - RemoveRequestHeader=Cookie

        # Game
        - id: game
          uri: ${services.game.url}          # http://localhost:8084
          predicates:
            - Path=/game-service/**
          filters:
            - RemoveRequestHeader=Cookie

        # Monitoring
        - id: monitoring
          uri: ${services.monitoring.url}    # http://localhost:8085
          predicates:
            - Path=/monitor-service/**
          filters:
            - RemoveRequestHeader=Cookie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

services:
  videosearch:
    url: http://youtube-search:8081
  encyclopedia:
    url: http://encyclopedia-search:8082
  news:
    url: http://news-tag-search:8083
  game:
    url: http://game-service:8084
  monitoring:
    url: http://monitoring:8085