server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # VideoSearch
        - id: video-search
          uri: http://video-service:8081    # http://localhost:8081
          predicates:
            - Path=/video-service/**          # /video-service/** 로 시작하는 요청 전부
          filters:
            - RemoveRequestHeader=Cookie      # Cookie 헤더만 삭제
            #- RewritePath=/video-service/(?<segment>.*), /$\{segment} # StripPrefix=1 로 대체 가능

        # Encyclopedia
        - id: encyclopedia
          uri: http://encyclopedia-service:8082  # http://localhost:8082
          predicates:
            - Path=/encyclopedia-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/encyclopedia-service/(?<segment>.*), /$\{segment}

        # News
        - id: news
          uri: http://news-service:8083          # http://localhost:8083
          predicates:
            - Path=/news-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/news-service/(?<segment>.*), /$\{segment}

        # Game
        - id: game
          uri: http://game-service:8084          # http://localhost:8084
          predicates:
            - Path=/game-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/game-service/(?<segment>.*), /$\{segment}

        # Monitoring
        - id: monitoring
          uri: http://monitor-service:8085    # http://localhost:8085
          predicates:
            - Path=/monitor-service/**
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/monitor-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka:8761/eureka/